---
spring:
  datasource:
    url: jdbc:h2:mem:blogdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
  session:
    store-type: none

logging:
  level:
    org:
      springframework:
        jdbc: DEBUG

app:
  kafka:
    enabled: false
